### PR TITLE
feat: support use ASSET_LOCATION env to declare asset location

### PR DESCRIPTION
**Pull request by cielpy**

### CODE REVIEW

**Comment by eycorsican** [comment]
Consider moving to https://github.com/eycorsican/leaf/blob/master/leaf/src/option/mod.rs

**Comment by cielpy** [comment]
I'm not familiar with Rust... and have a try but failed...

**Comment by eycorsican** [comment]
That's fine, I'll implement this feature later, thanks for the pr.

**Comment by cielpy** [comment]
Thanks!

**Pull request closed without merging**
